### ISSUE TITLE
Not installing in Ubuntu 14.04 

### ISSUE THREAD

**Issue by deepakjnath** [msbrogli/sdm-framework#2]
Does this work with Ubuntu 14.04?

**Comment by msbrogli** [comment]
@deepakjnath It is supposed to work. We tested v1.0.1 in an Amazon Linux and it worked fine. Can you copy your error message here?

**Comment by msbrogli** [comment]
I created a virtual machine with Ubuntu 14.04 and the only problem I saw was when OpenCL is not installed. In fact, it is only required in `scanner_opencl.c`, which could be optional. Was it your error?

**Comment by JadenTravnik** [comment]
Hi, I am trying to install it on Ubuntu 14.04 as well. When i try:
`$ python setup.py install` 
I get the scanner_opencl error you mentioned, specifically:

```
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DSDM_USE_BITCOUNT_TABLE -DSDM_ENABLE_OPENCL -DOS_LINUX -I/usr/include/python2.7 -c src/scanner_opencl.c -o build/temp.linux-x86_64-2.7/src/scanner_opencl.o
In file included from src/scanner_opencl.c:6:0:
src/scanner_opencl.h:10:19: fatal error: CL/cl.h: No such file or directory
 #include <CL/cl.h>
                   ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

I have opencl installed (1.2 (Build 57))

Any suggestions?

**Comment by Alex-Linhares** [comment]
@JadenTravnik Can you post the result of the command:

    clinfo 

On your terminal, please?

**Comment by JadenTravnik** [comment]
Sorry, won't be able to. Changed computers since then.

**Comment by Alex-Linhares** [comment]
Also got errors on two machines.  This is from a 13 macbook pro: 


    MacRetina13:~ AL$ pip install sdm Collecting sdm /Users/AL/anaconda/lib/python2.7/site-packages/pip/vendor/requests/packages/urllib3/util/ssl.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, seehttps://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning. SNIMissingWarning /Users/AL/anaconda/lib/python2.7/site-packages/pip/vendor/requests/packages/urllib3/util/ssl.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, seehttps://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning. InsecurePlatformWarning Downloading sdm-1.0.1.tar.gz Installing collected packages: sdm Running setup.py install for sdm ... done Successfully installed sdm-1.0.1 /Users/AL/anaconda/lib/python2.7/site-packages/pip/vendor/requests/packages/urllib3/util/ssl.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, seehttps://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning. InsecurePlatformWarning
=========

**Comment by Alex-Linhares** [comment]
And this from a *very* old linux box... that should not install anyways (doesn't have openCL).  Here's the dump: 

        gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DSDM_USE_BITCOUNT_TABLE -DSDM_ENABLE_OPENCL -DOS_LINUX -I/home/username/anaconda/include/python2.7 -c src/scanner_opencl.c -o build/temp.linux-x86_64-2.7/src/scanner_opencl.o
    In file included from src/scanner_opencl.c:6:0:
    src/scanner_opencl.h:10:19: fatal error: CL/cl.h: No such file or directory
     #include <CL/cl.h>
=======

**Comment by msbrogli** [comment]
Let me know if you're experiencing installation issues.
